# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: License check preparation
on:
  # TEMP: run from PR, instead of from pull_request_target.
  # No access to secrets this way!
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  pull-requests: write
  issues: write


jobs:
  license-check:
    name: Self Scan (from Action)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run dash-license-scan from experimental @dev branch
      - uses: eclipse-score/dash-license-scan@dev
        with:
          token: ${{ secrets.ECLIPSE_GITLAB_API_TOKEN }}
          eclipse_project: ${{ vars.ECLIPSE_PROJECT }}
          lockfiles: src/requirements.txt
          trigger_review: false
          comply_with: ASF EF
